# Generated by Django 4.1.2 on 2022-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('WA', 'WATCHES')], max_length=2),
        ),
    ]
