# Generated by Django 4.1.2 on 2022-10-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'men'), ('W', 'women'), ('WA', 'watches')], max_length=2),
        ),
    ]
